nelmio_api_doc:
    documentation:
        info:
            title: Productpedia
            description: The main goal is gather and systematize various informations about products.
            version: 0.0.1a
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
